name: 'pindakaas&mandelmus'
favicon: null
layout_spectrum: 0.5110318465158343
typography_spectrum: 0.8039860147982836
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.0008840709924697876
  lightness: 0.9028099903371185
  saturation: 0.5115325499791652
  rhythmicContrast: 0.9609349272213876
purpose: []
